### Проверить состояние сервиса
GET http://localhost:8080/ping HTTP/1.1
Accept: application/json

### Получить список всех блюд
GET http://localhost:8080/dishes HTTP/1.1
Accept: application/json

### Получить конкретное блюдо по ID
GET http://localhost:8080/dishes/019c1fb8-1f21-76f0-8ba5-472ab6e35c96 HTTP/1.1
Accept: application/json

### Добавить новое блюдо
POST http://localhost:8080/dishes HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  "name": "Колбаса",
  "description": "Куриная колбаса.",
  "price": 7.99,
  "imageUrl": "http://example.com/sausage.jpg",
  "weight": 3,
  "unit": "шт."
}

### Обновить блюдо
PATCH http://localhost:8080/dishes/019c1fb8-1f21-76f0-8ba5-472ab6e35c96 HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  "weight": 4
}

### Удалить блюдо
DELETE http://localhost:8080/dishes/019c1fb8-1f21-76f0-8ba5-472ab6e35c96 HTTP/1.1