services:
  # --- GATEWAY ---
  yarp:
    build:
      context: ../YARP
    image: yarp-gateway:latest
    ports:
      - "8080:80"
    depends_on:
      dishservice:
        condition: service_healthy
      orderservice:
        condition: service_healthy
      authservice:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - backend

  # --- SERVICES ---
  authservice:
    build:
      context: ../AuthService
    image: authservice:latest
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT-Development}
      - ConnectionStrings__DefaultConnection=Host=authservice-db;Port=5432;Database=${AUTH_DB_NAME};Username=${AUTH_DB_USER};Password=${AUTH_DB_PASSWORD}
      - ConnectionStrings__Redis=authservice-redis:6379,abortConnect=false,connectRetry=5,connectTimeout=5000
      - SWAGGER_BASEPATH=/auth
      - Jwt__Key=${JWT_KEY}
    depends_on:
      authservice-db:
        condition: service_healthy
      authservice-redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- --timeout=2 http://127.0.0.1/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  dishservice:
    build:
      context: .
    image: dishservice:latest
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT-Development}
      - ConnectionStrings__DefaultConnection=Host=dishservice-db;Port=5432;Database=${DISH_DB_NAME};Username=${DISH_DB_USER};Password=${DISH_DB_PASSWORD}
      - ConnectionStrings__Redis=dishservice-redis:6379,abortConnect=false,connectRetry=5,connectTimeout=5000
      - SWAGGER_BASEPATH=/dishes
    depends_on:
      dishservice-db:
        condition: service_healthy
      dishservice-redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- --timeout=2 http://127.0.0.1/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  orderservice:
    build:
      context: ../OrderService
    image: orderservice:latest
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT-Development}
      - ConnectionStrings__DefaultConnection=Host=orderservice-db;Port=5432;Database=${ORDER_DB_NAME};Username=${ORDER_DB_USER};Password=${ORDER_DB_PASSWORD}
      - ConnectionStrings__Redis=orderservice-redis:6379,abortConnect=false,connectRetry=5,connectTimeout=5000
      - SWAGGER_BASEPATH=/orders
    depends_on:
      orderservice-db:
        condition: service_healthy
      orderservice-redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- --timeout=2 http://127.0.0.1/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # --- DATABASES ---
  authservice-db:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: ${AUTH_DB_USER}
      POSTGRES_PASSWORD: ${AUTH_DB_PASSWORD}
      POSTGRES_DB: ${AUTH_DB_NAME}
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${AUTH_DB_USER} -d ${AUTH_DB_NAME} || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 10s

  dishservice-db:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: ${DISH_DB_USER}
      POSTGRES_PASSWORD: ${DISH_DB_PASSWORD}
      POSTGRES_DB: ${DISH_DB_NAME}
    volumes:
      - dish_db_data:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DISH_DB_USER} -d ${DISH_DB_NAME} || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 10s

  orderservice-db:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: ${ORDER_DB_USER}
      POSTGRES_PASSWORD: ${ORDER_DB_PASSWORD}
      POSTGRES_DB: ${ORDER_DB_NAME}
    volumes:
      - orderservice_db_data:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${ORDER_DB_USER} -d ${ORDER_DB_NAME} || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 10s

  # --- CACHE ---
  dishservice-redis:
    image: redis:8.4-alpine
    volumes:
      - dish_redis_data:/data
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  orderservice-redis:
    image: redis:8.4-alpine
    volumes:
      - orderservice_redis_data:/data
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  authservice-redis:
    image: redis:8.4-alpine
    volumes:
      - auth_redis_data:/data
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

networks:
  backend:
    driver: bridge

volumes:
  auth_db_data:
  dish_db_data:
  orderservice_db_data:
  dish_redis_data:
  orderservice_redis_data:
  auth_redis_data:
