// <auto-generated />
using System;
using DishService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DishService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DishService.Models.Dish", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_available");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("SoldBy")
                        .HasColumnType("integer")
                        .HasColumnName("sold_by");

                    b.HasKey("Id")
                        .HasName("pk_dishes");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_dishes_name");

                    b.ToTable("dishes", (string)null);
                });

            modelBuilder.Entity("DishService.Models.DishPriceOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DishId")
                        .HasColumnType("uuid")
                        .HasColumnName("dish_id");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("price");

                    b.Property<decimal>("UnitAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("unit_amount");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unit_of_measure");

                    b.HasKey("Id")
                        .HasName("pk_dish_price_options");

                    b.HasIndex("DishId")
                        .HasDatabaseName("ix_dish_price_options_dish_id");

                    b.ToTable("dish_price_options", (string)null);
                });

            modelBuilder.Entity("DishService.Models.DishPriceOption", b =>
                {
                    b.HasOne("DishService.Models.Dish", null)
                        .WithMany("PriceOptions")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_dish_price_options_dishes_dish_id");
                });

            modelBuilder.Entity("DishService.Models.Dish", b =>
                {
                    b.Navigation("PriceOptions");
                });
#pragma warning restore 612, 618
        }
    }
}
